name: Accelerator CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r accelerator/requirements.txt
          pip install sqlfluff

      - name: Lint SQL
        run: |
          sqlfluff lint accelerator/module2_automation/weekly_margin/scripts/weekly_margin.sql --config accelerator/module2_automation/weekly_margin/ci/sqlfluff.yml

      - name: Run pytest
        env:
          PYTHONPATH: accelerator
        run: |
          pytest accelerator/module4_modernization/tests
